### ISSUE TITLE
Why fifo must have 2 to the power of N(Natural number) elements?

### ISSUE THREAD

**Issue by Dicklessgreat** [hogliux/farbot#4]
Just from my curiosity... could you tell me why number of elements in the fifo must be 2 ^ N?
I took this line that capacity must be 2 ^ N, which I have not mathematically proven(Tell me if it's wrong!).
https://github.com/hogliux/farbot/blob/914e21875ce6a92d15d3b8442f5ece94093f7d21/fifo.tcc#L180

**Comment by paulfd** [comment]
It simplifies the operations on the ring buffer (and quite smartly so ;-))

https://stackoverflow.com/questions/10527581/why-must-a-ring-buffer-size-be-a-power-of-2

**Comment by Dicklessgreat** [comment]
Ah! I got it!
It really blows my mind!!
Thank you for your answer. You made my day!
