### ISSUE TITLE
Can't use realtime object in class templates

### ISSUE THREAD

**Issue by walleym** [hogliux/farbot#8]
From what I can see realtime object does not work with class templates. This does not compile:

```
template<typename FloatType>
class Test
{
public:
    Test()
    {
        farbot::RealtimeObject<std::vector<FloatType>, farbot::RealtimeObjectOptions::nonRealtimeMutatable> obj;
        farbot::RealtimeObject<std::vector<FloatType>, farbot::RealtimeObjectOptions::nonRealtimeMutatable>::ScopedAccess<farbot::ThreadType::nonRealtime> t(obj);
        
        t->push_back(6.0);
    }
};
```

Why is this?

**Comment by anbjoernskov** [comment]
Check out this other issue, which describes how to use 'typename' and 'template' keywords. So in your case it should be 

`typename farbot::RealtimeObject<std::vector<FloatType>, farbot::RealtimeObjectOptions::nonRealtimeMutatable>::template ScopedAccess<farbot::ThreadType::nonRealtime> t(obj);`

**Comment by walleym** [comment]
Thanks!
